# Site settings
title: Phares Phun
description: One stop shop for all my things productivity related
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://localhost:3000"
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Andrew Phares
user_description: A peculiar fellow who sometimes codes, and sometimes does other things.
user_title: Developer & Designer
email: aphares3849@gmail.com

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
